[book]
title = "Tutorial de Siliwiz"
authors = ["obijuan"]
language = "en"
src = "src"

[build]
build-dir = "book"

# Habilita el preprocesador de KaTeX
[preprocessor.katex]

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
mathjax-support = false # Desactivado a favor de KaTeX
