name: Deploy mdBook to GitHub Pages

on:
  push:
    branches: ["main"] # Cambia a "master" si tu rama principal se llama así

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      # Instala la herramienta de instalación rápida de binarios precompilados en Rust
      - name: Instalar cargo-binstall
        uses: cargo-bins/cargo-binstall-action@v1.10.2

      # Instala mdbook-katex usando el binario precompilado (tarda ~2 segundos)
      - name: Instalar mdbook-katex
        run: cargo binstall --no-confirm mdbook-katex

      - name: Compilar la documentación (Generar HTML)
        run: mdbook build

      - name: Subir artefactos de la web
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
