name: Deploy mdBook to GitHub Pages

on:
  push:
    branches: ["main"]

# Opciones de permisos necesarias para desplegar en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue simultáneo a la vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
          # Si usas plugins como mdbook-katex o mdbook-toc, los puedes añadir aquí:
          # recipes: 'mdbook-katex'

      - name: Compilar la documentación (Generar HTML)
        run: mdbook build

      - name: Subir artefactos de la web
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book # Carpeta donde mdBook guarda el HTML generado

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

